[project]
name = "gleaf"
version = "0.1.0"
description = "An adaptive, high-performance terminal canvas library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    # list your actual runtime dependencies here if any
]

[build-system]
requires = ["uv_build>=0.11.24,<0.12.0"]
build-backend = "uv_build"
